<a href="https://colab.research.google.com/github/codefluorite/tensorflow/blob/main/TensorFlow_Introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import tensorflow

In [1]:
%tensorflow_version 2.x # states the line to use

`%tensorflow_version` only switches the major version: 1.x or 2.x.
You set: `2.x # states the line to use`. This will be interpreted as: `2.x`.


TensorFlow 2.x selected.


In [2]:
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.7/dist-packages/tensorflow/_api/v2/version/__init__.py'>


Tensors - a vector generalised to higher dimensions

In [3]:
string = tf.Variable("This is a string", tf.string)
number = tf.Variable(324, tf.int16)
floating = tf.Variable(3.564, tf.float64)

Rank

The number of dimensions

In [4]:
rank1_tensor = tf.Variable(["Test", "Ok", "codefluorite"], tf.string)
rank2_tensor = tf.Variable([["test", "ok"], ["test", "ok"]], tf.string)

To determine the rank of a tensor

In [5]:
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

To determine the shape of a tensor

In [6]:
rank2_tensor.shape

TensorShape([2, 2])

Changing shape

Reshape the data

In [7]:
tensor1 = tf.ones([1,2,3]) # tf.ones() creates a shape [1,2,3] tensor full of ones
tensor2 = tf.reshape(tensor1, [2,3,1]) # reshapes exsisting data to shape [2,3,1]
tensor3 = tf.reshape(tensor2, [3, -1]) # -1 tells the tensor to calculat the size of the dimension in that place
                                      # this will rehape the tensor to [3,2]

# The number of elements in the reshaped tensor must match the number in the original

In [8]:
print(tensor1)
print(tensor2)
print(tensor3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


Types of tensor



*   Variable
*   Constant
*   Placeholder
*   SparseTensor

Evaluating Tensors

Evaluate a tensors value. 

In [ ]:
with tf.session() as sess: # creates a session using the default graph
  tensor.eval() # tensor will of course be the name of your tensor

Sources:

https://tensorflow.org/guide/tensor